import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from scipy.signal import find_peaks

import torch
import torch.nn as nn
import torch.optim as optim
import optuna

# Script generated by Google Gemini and debugged by me

plt.switch_backend('Agg')


# ==========================================
# 1. SETUP & SEEDS
# ==========================================
def set_seeds(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ['PYTHONHASHSEED'] = str(seed)


set_seeds(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


# ==========================================
# 2. HELPER FUNCTIONS & DATA LOGIC
# ==========================================
def mode(probs): return np.argmax(probs) + 1


def predictive_entropy(probs, eps=1e-8):
    probs = np.clip(probs, eps, 1.0)
    return -np.sum(probs * np.log(probs))


def kl_divergence(p, q, eps=1e-8):
    p = np.clip(p, eps, 1.0)
    q = np.clip(q, eps, 1.0)
    return np.sum(p * np.log(p / q))


def addFeatures(trueState, time, patientProbs, prevPatientProbs, last_observed_state, time_since_last_scan):
    mHat = mode(patientProbs)
    mHatLast = mode(prevPatientProbs)
    uncert = predictive_entropy(patientProbs)
    prevUncert = predictive_entropy(prevPatientProbs)
    diverge = kl_divergence(patientProbs, prevPatientProbs)

    output = np.zeros(23, dtype='float')
    output[0] = trueState if not np.isnan(trueState) else 0.0
    output[1] = mHat
    output[2] = mHatLast
    output[3] = mHat - mHatLast
    output[4] = uncert
    output[5] = prevUncert
    output[6] = uncert - prevUncert
    output[7] = diverge
    output[8] = time
    for i in range(4):
        output[i + 9] = patientProbs[i]
        output[i + 13] = prevPatientProbs[i]
        output[i + 17] = patientProbs[i] - prevPatientProbs[i]

    output[21] = last_observed_state if not np.isnan(last_observed_state) else 0.0
    output[22] = time_since_last_scan
    return output


def get_peak_indices_tuned(rewards, threshold=0.028):
    T = len(rewards)
    if T == 0: return []
    peaks, _ = find_peaks(rewards, height=threshold, prominence=1e-5)
    candidates = set(peaks)
    glob_max_idx = np.argmax(rewards)
    if rewards[glob_max_idx] >= threshold: candidates.add(glob_max_idx)
    if T > 0 and rewards[0] >= threshold:
        if T == 1 or rewards[0] >= rewards[1]: candidates.add(0)
    if T > 1 and rewards[-1] >= threshold:
        if rewards[-1] >= rewards[-2]: candidates.add(T - 1)
    return sorted(list(candidates))


class Patient:
    def __init__(self, patient_id, patient_rewards, delay_values, features, patient_scans, T):
        self.id = patient_id
        self.features = features
        self.T = T
        self.rewards = patient_rewards
        self.delay_values = delay_values
        self.scans = patient_scans

    def get_context(self, t, window=2):
        indices = np.arange(t - window + 1, t + 1)
        indices = np.maximum(indices, 0)
        return self.features[indices, :].flatten()

    def get_targets(self, t):
        if t + 3 > self.T:
            padding = np.zeros(3 - (self.T - t))
            rewards_window = np.concatenate([self.rewards[t:], padding])
        else:
            rewards_window = self.rewards[t:t + 3]

        delay_val = np.array([self.delay_values[t]])
        return np.concatenate([rewards_window, delay_val])


def create_patient_objects(df, horizon_T=3):
    patient_objects = []
    for pid, group in df.groupby('ptid_idx'):
        group = group.sort_values('hour').reset_index(drop=True)
        scan_indices = group.index[group['true_scans'] == 1].tolist()
        if not scan_indices: continue

        first_scan_idx = scan_indices[0]
        remaining_stay_df = group.iloc[first_scan_idx:].reset_index(drop=True)
        total_stay = len(remaining_stay_df)

        if total_stay >= horizon_T:
            initial_state = remaining_stay_df['last_known_mls_class'].iloc[0]
            probs_matrix = remaining_stay_df[['proba_0', 'proba_1', 'proba_2', 'proba_3']].values
            rewards = remaining_stay_df['proxy_reward'].values
            delay_values = remaining_stay_df['scan_delay_value'].values
            scans = remaining_stay_df['true_scans'].values
            hours = remaining_stay_df['hour'].values

            feature_list = []
            last_scan_hour = hours[0]
            last_observed_state = initial_state

            for t in range(total_stay):
                if scans[t] == 1:
                    last_scan_hour = hours[t]
                    last_observed_state = remaining_stay_df['last_known_mls_class'].iloc[t]

                time_since_last_scan = hours[t] - last_scan_hour
                current_probs = probs_matrix[t]
                prev_probs = probs_matrix[t - 1] if t > 0 else (np.ones(4) / 4.0)

                feat_vec = addFeatures(initial_state, hours[t], current_probs, prev_probs,
                                       last_observed_state, time_since_last_scan)
                feature_list.append(feat_vec)

            p = Patient(patient_id=pid, patient_rewards=rewards, delay_values=delay_values,
                        features=np.array(feature_list), patient_scans=scans, T=total_stay)
            patient_objects.append(p)
    return patient_objects


def generate_maps(patients, target_w=0.028):
    act_map, triv_map = [], []
    for p_idx, p in enumerate(patients):
        true_peak_indices = set(get_peak_indices_tuned(p.rewards, threshold=target_w))
        for t in range(p.T - 2):
            if not {t, t + 1, t + 2}.isdisjoint(true_peak_indices):
                act_map.append((p_idx, t))
            else:
                triv_map.append((p_idx, t))
    return act_map, triv_map


# ==========================================
# 3. CLASSIFIER SPECIFIC LOGIC
# ==========================================
def get_classification_labels(s_batch, kappa=0.028):
    """
    Converts continuous targets into discrete optimal action labels.
    0: Scan t, 1: Scan t+1, 2: Scan t+2, 3: Defer
    """
    if not isinstance(s_batch, torch.Tensor):
        s_batch = torch.tensor(s_batch, dtype=torch.float32)

    objective_values = s_batch.clone()
    # Subtract kappa only from the scan options (indices 0, 1, 2)
    objective_values[:, :3] = objective_values[:, :3] - kappa
    return torch.argmax(objective_values, dim=1)


def calculate_class_weights(patients, kappa=0.028):
    """Calculates inverse frequency weights for the CrossEntropyLoss."""
    all_labels = []
    for p in patients:
        for t in range(p.T - 2):
            targets = p.get_targets(t)
            obj_vals = np.copy(targets)
            obj_vals[:3] -= kappa
            all_labels.append(np.argmax(obj_vals))

    classes = np.array([0, 1, 2, 3])
    weights = compute_class_weight(class_weight='balanced', classes=classes, y=all_labels)
    return torch.tensor(weights, dtype=torch.float32)


class ClassifierNet(nn.Module):
    def __init__(self, input_dim=46, hidden_dim=512, dropout_rate=0.1):
        super().__init__()
        self.num_classes = 4
        last_dim = hidden_dim // 2

        self.trunk = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.ReLU(), nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.ReLU(), nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, last_dim), nn.LayerNorm(last_dim), nn.ReLU(),
        )
        # Outputs 4 raw logits for CrossEntropyLoss
        self.target_head = nn.Linear(last_dim, self.num_classes)

    def forward(self, x):
        return self.target_head(self.trunk(x))


# ==========================================
# 4. DATA SAMPLERS
# ==========================================
def sample_independent_windows(patients, act_map, triv_map, batch_size, actionable_ratio=0.5):
    n_act = int(batch_size * actionable_ratio)
    n_triv = batch_size - n_act

    act_indices = [act_map[i] for i in np.random.choice(len(act_map), n_act)]
    triv_indices = [triv_map[i] for i in np.random.choice(len(triv_map), n_triv)]
    combined = act_indices + triv_indices
    np.random.shuffle(combined)

    contexts, targets = [], []
    for p_idx, t in combined:
        p = patients[p_idx]
        contexts.append(p.get_context(t))
        targets.append(p.get_targets(t))

    return torch.tensor(np.array(contexts), dtype=torch.float32), \
        torch.tensor(np.array(targets), dtype=torch.float32)


def sample_natural_independent_windows(patients, batch_size):
    all_x, all_s = [], []
    patient_indices = np.random.choice(len(patients), batch_size, replace=True)

    for p_idx in patient_indices:
        p = patients[p_idx]
        t = np.random.randint(0, p.T - 2)
        all_x.append(p.get_context(t))
        all_s.append(p.get_targets(t))

    return torch.tensor(np.array(all_x), dtype=torch.float32), \
        torch.tensor(np.array(all_s), dtype=torch.float32)


# ==========================================
# 5. OPTUNA OBJECTIVE
# ==========================================
def objective_classifier(trial, train_patients, val_patients, train_act, train_triv, class_weights):
    lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    weight_decay = trial.suggest_float("weight_decay", 1e-5, 1e-2, log=True)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])
    hidden_dim = trial.suggest_categorical('hidden_dim', [256, 512])
    actionable_ratio = trial.suggest_float("actionable_ratio", 0.3, 0.7)

    model = ClassifierNet(input_dim=46, hidden_dim=hidden_dim).to(device)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    # Using the pre-calculated weights
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))

    epochs = 40
    steps_per_epoch = 100
    val_steps = 50
    best_macro_f1 = 0.0

    for epoch in range(epochs):
        model.train()
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(
                train_patients, train_act, train_triv, batch_size=batch_size, actionable_ratio=actionable_ratio
            )
            x_batch = x_batch.to(device)
            labels = get_classification_labels(s_batch).to(device)

            optimizer.zero_grad()
            logits = model(x_batch)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

        model.eval()
        all_val_preds = []
        all_val_labels = []

        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size=batch_size)
                labels = get_classification_labels(s_val).numpy()
                logits = model(x_val.to(device))
                preds = torch.argmax(logits, dim=1).cpu().numpy()

                all_val_labels.extend(labels)
                all_val_preds.extend(preds)

        macro_f1 = f1_score(all_val_labels, all_val_preds, average='macro', zero_division=0)

        trial.report(macro_f1, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

        if macro_f1 > best_macro_f1:
            best_macro_f1 = macro_f1

    return best_macro_f1


# ==========================================
# 6. VISUALIZATIONS
# ==========================================
def plot_confusion_matrix(model, patients, filename='confusion_matrix.png'):
    model.eval()
    all_preds, all_labels = [], []

    with torch.no_grad():
        # Large natural sample to get a realistic evaluation of the matrix
        x_val, s_val = sample_natural_independent_windows(patients, batch_size=2000)
        labels = get_classification_labels(s_val).numpy()
        logits = model(x_val.to(device))
        preds = torch.argmax(logits, dim=1).cpu().numpy()

        all_labels.extend(labels)
        all_preds.extend(preds)

    cm = confusion_matrix(all_labels, all_preds)
    class_names = ['Scan t', 'Scan t+1', 'Scan t+2', 'Defer']

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title('Validation Confusion Matrix', fontsize=14, fontweight='bold')
    plt.ylabel('True Optimal Action')
    plt.xlabel('Predicted Action')
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()
    print(f"Saved confusion matrix to {filename}")


# ==========================================
# MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    print("Loading data for Multiclass Baseline...")
    dfV = pd.read_csv("HELMET_Triangular_Targets_with_V.csv")
    patientArray = create_patient_objects(dfV)
    train_patients, temp_patients = train_test_split(patientArray, test_size=0.30, random_state=42)
    val_patients, test_patients = train_test_split(temp_patients, test_size=0.50, random_state=42)

    train_act, train_triv = generate_maps(train_patients)

    print("Calculating Class Weights...")
    class_weights = calculate_class_weights(train_patients)
    print(f"Class Weights: {class_weights.numpy()}")

    print("Starting Phase 1 Classifier Optuna Study...")
    study_class = optuna.create_study(
        direction='maximize',  # Note: Maximizing Macro F1
        study_name='new_classifier_study',
        storage='sqlite:///optuna_new_classifier_study.db',
        load_if_exists=True,
        pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5)
    )

    study_class.optimize(
        lambda trial: objective_classifier(trial, train_patients, val_patients, train_act, train_triv, class_weights),
        n_trials=60
    )

    print(f"Best Classifier Params: {study_class.best_params}")

    # ----------------------------------------
    # Train Final Model with Best Hyperparameters
    # ----------------------------------------
    best_lr = study_class.best_params['lr']
    best_wd = study_class.best_params['weight_decay']
    best_batch = study_class.best_params['batch_size']
    best_ratio = study_class.best_params['actionable_ratio']
    best_hidden = study_class.best_params['hidden_dim']

    print(f"\n--- Training Final Classifier Model ---")
    final_model = ClassifierNet(input_dim=46, hidden_dim=best_hidden).to(device)
    optimizer = optim.AdamW(final_model.parameters(), lr=best_lr, weight_decay=best_wd)
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))

    epochs = 40
    steps_per_epoch = 100
    val_steps = 50

    for epoch in range(epochs):
        final_model.train()
        train_f1_list = []
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(
                train_patients, train_act, train_triv, batch_size=best_batch, actionable_ratio=best_ratio
            )
            x_batch = x_batch.to(device)
            labels = get_classification_labels(s_batch).to(device)

            optimizer.zero_grad()
            logits = final_model(x_batch)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            preds = torch.argmax(logits, dim=1).cpu().numpy()
            train_f1_list.append(f1_score(labels.cpu().numpy(), preds, average='macro', zero_division=0))

        avg_train_f1 = np.mean(train_f1_list)

        final_model.eval()
        all_val_preds, all_val_labels = [], []
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size=best_batch)
                labels = get_classification_labels(s_val).numpy()
                logits = final_model(x_val.to(device))
                preds = torch.argmax(logits, dim=1).cpu().numpy()

                all_val_labels.extend(labels)
                all_val_preds.extend(preds)

        val_macro_f1 = f1_score(all_val_labels, all_val_preds, average='macro', zero_division=0)
        print(f"Epoch {epoch + 1}/{epochs} | Train Macro F1: {avg_train_f1:.4f} | Val Macro F1: {val_macro_f1:.4f}")

    torch.save(final_model.state_dict(), 'rewardnet_new_classifier_best.pth')
    print("Final model saved to rewardnet_new_classifier_best.pth")

    print("\nGenerating Visualizations...")
    plot_confusion_matrix(final_model, val_patients, filename="classifier_confusion_matrix.png")