import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.signal import find_peaks
from sklearn.model_selection import train_test_split
import random
import optuna

# Script generated by Google Gemini and debugged by me

plt.switch_backend('Agg')


# ==========================================
# 1. SETUP & SEEDS
# ==========================================
def set_seeds(seed=42):
    """Sets random seeds for reproducible results."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ['PYTHONHASHSEED'] = str(seed)
    print(f"Random seeds set to {seed}")


set_seeds(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================

def sample_natural_independent_windows(patients, batch_size):
    all_x, all_s = [], []
    patient_indices = np.random.choice(len(patients), batch_size, replace=True)

    for p_idx in patient_indices:
        p = patients[p_idx]
        t = np.random.randint(0, p.T - 2)
        all_x.append(p.get_context(t))
        all_s.append(p.get_targets(t))  # NEW: Changed from get_rewards to get_targets

    return torch.tensor(np.array(all_x), dtype=torch.float32), \
        torch.tensor(np.array(all_s), dtype=torch.float32)


def mode(probs):
    return np.argmax(probs) + 1


def predictive_entropy(probs, eps=1e-8):
    probs = np.clip(probs, eps, 1.0)
    return -np.sum(probs * np.log(probs))


def kl_divergence(p, q, eps=1e-8):
    p = np.clip(p, eps, 1.0)
    q = np.clip(q, eps, 1.0)
    return np.sum(p * np.log(p / q))


def MSE(y_pred, y_true):
    return np.sum((y_pred - y_true) ** 2)


# NEW: Updated to include last_observed_state and time_since_last_scan
def addFeatures(trueState, time, patientProbs, prevPatientProbs, last_observed_state, time_since_last_scan):
    mHat = mode(patientProbs)
    mHatLast = mode(prevPatientProbs)
    uncert = predictive_entropy(patientProbs)
    prevUncert = predictive_entropy(prevPatientProbs)
    diverge = kl_divergence(patientProbs, prevPatientProbs)

    # NEW: Increased output size from 21 to 23
    output = np.zeros(23, dtype='float')
    output[0] = trueState if not np.isnan(trueState) else 0.0
    output[1] = mHat
    output[2] = mHatLast
    output[3] = mHat - mHatLast
    output[4] = uncert
    output[5] = prevUncert
    output[6] = uncert - prevUncert
    output[7] = diverge
    output[8] = time

    for i in range(4):
        output[i + 9] = patientProbs[i]
        output[i + 13] = prevPatientProbs[i]
        output[i + 17] = patientProbs[i] - prevPatientProbs[i]

    # NEW: Added clinical features (handling NaNs if no scans occurred yet)
    output[21] = last_observed_state if not np.isnan(last_observed_state) else 0.0
    output[22] = time_since_last_scan

    return output


def get_peak_indices_tuned(rewards, threshold=0.028):
    T = len(rewards)
    if T == 0:
        return []
    peaks, _ = find_peaks(rewards, height=threshold, prominence=1e-5)
    candidates = set(peaks)
    glob_max_idx = np.argmax(rewards)
    if rewards[glob_max_idx] >= threshold:
        candidates.add(glob_max_idx)
    if T > 0 and rewards[0] >= threshold:
        if T == 1 or rewards[0] >= rewards[1]:
            candidates.add(0)
    if T > 1 and rewards[-1] >= threshold:
        if rewards[-1] >= rewards[-2]:
            candidates.add(T - 1)
    return sorted(list(candidates))


# ==========================================
# 3. CLASSES (PATIENT & MODELS)
# ==========================================
class Patient:
    # NEW: Include delay_values in init
    def __init__(self, patient_id, patient_rewards, delay_values, features, patient_scans, T):
        self.id = patient_id
        self.features = features
        self.T = T
        self.rewards = patient_rewards
        self.delay_values = delay_values
        self.scans = patient_scans
        self.reset_state()

    def reset_state(self):
        self.last_scan_time = -float('inf')

    def get_id(self):
        return self.id

    def get_context(self, t, window=2):
        indices = np.arange(t - window + 1, t + 1)
        indices = np.maximum(indices, 0)
        block = self.features[indices, :]
        return block.flatten()

    # NEW: Replaced get_rewards with get_targets to return [R_t, R_t+1, R_t+2, V_t]
    def get_targets(self, t):
        if t + 3 > self.T:
            padding = np.zeros(3 - (self.T - t))
            rewards_window = np.concatenate([self.rewards[t:], padding])
        else:
            rewards_window = self.rewards[t:t + 3]

        delay_val = np.array([self.delay_values[t]])
        return np.concatenate([rewards_window, delay_val])

    def get_scans(self, t):
        if t + 3 > self.T:
            return self.scans[t:]
        return self.scans[t:t + 3]


class ScaledHuberModelWrapper(torch.nn.Module):
    def __init__(self, base_model, scale_factor=25.0):
        super().__init__()
        self.base_model = base_model
        self.scale_factor = scale_factor

    def forward(self, x):
        return self.base_model(x) * self.scale_factor


# ==========================================
# 4. DATA PROCESSING & SAMPLERS
# ==========================================
def create_patient_objects(df, horizon_T=3):
    patient_objects = []
    grouped = df.groupby('ptid_idx')
    print(f"Processing {len(grouped)} unique patients...")
    for pid, group in grouped:
        group = group.sort_values('hour').reset_index(drop=True)
        scan_indices = group.index[group['true_scans'] == 1].tolist()
        if not scan_indices:
            continue

        first_scan_idx = scan_indices[0]
        remaining_stay_df = group.iloc[first_scan_idx:].reset_index(drop=True)
        total_stay_after_scan = len(remaining_stay_df)

        if total_stay_after_scan >= horizon_T:
            initial_state = remaining_stay_df['last_known_mls_class'].iloc[0]
            probs_cols = ['proba_0', 'proba_1', 'proba_2', 'proba_3']
            probs_matrix = remaining_stay_df[probs_cols].values
            rewards = remaining_stay_df['proxy_reward'].values

            # NEW: Extract delay targets
            delay_values = remaining_stay_df['scan_delay_value'].values

            scans = remaining_stay_df['true_scans'].values
            hours = remaining_stay_df['hour'].values
            feature_list = []

            # NEW: Track clinical variables for the loop
            last_scan_hour = hours[0]
            last_observed_state = initial_state

            for t in range(total_stay_after_scan):
                # NEW: Update the clinical variables if a scan happened
                if scans[t] == 1:
                    last_scan_hour = hours[t]
                    last_observed_state = remaining_stay_df['last_known_mls_class'].iloc[t]

                time_since_last_scan = hours[t] - last_scan_hour
                current_probs = probs_matrix[t]
                prev_probs = probs_matrix[t - 1] if t > 0 else (np.ones(4) / 4.0)

                # NEW: Pass clinical features into addFeatures
                feat_vec = addFeatures(
                    initial_state, hours[t], current_probs, prev_probs,
                    last_observed_state, time_since_last_scan
                )
                feature_list.append(feat_vec)

            # NEW: Initialize Patient object with delay_values
            p = Patient(patient_id=pid, patient_rewards=rewards, delay_values=delay_values,
                        features=np.array(feature_list), patient_scans=scans, T=total_stay_after_scan)
            patient_objects.append(p)

    print(f"Successfully instantiated {len(patient_objects)} Patient objects.")
    return patient_objects


def objective_huber(trial, train_patients, val_patients, train_act, train_triv):
    # 1. Suggest Hyperparameters
    lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)
    weight_decay = trial.suggest_float("weight_decay", 1e-5, 1e-2, log=True)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])
    scale_factor = trial.suggest_categorical("scale_factor", [1.0, 25.0, 50.0, 100.0])
    hidden_dim = trial.suggest_categorical('hidden_dim', [256, 512])
    actionable_ratio = trial.suggest_float("actionable_ratio", 0.3, 0.7)

    # NEW: Suggest Huber delta (threshold between L1 and L2 loss)
    delta = trial.suggest_float("delta", 0.05, 5.0, log=True)

    base_model = DirectRewardNet(input_dim=46, hidden_dim=hidden_dim, T=3).to(device)
    model = ScaledHuberModelWrapper(base_model, scale_factor=scale_factor).to(device)

    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    # NEW: Initialize Huber loss with the tuned delta
    criterion = nn.HuberLoss(delta=delta)

    epochs = 40
    steps_per_epoch = 100
    val_steps = 50
    best_val_loss = float('inf')

    # 3. Training Loop
    for epoch in range(epochs):
        model.train()
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(
                train_patients, train_act, train_triv, batch_size=batch_size, actionable_ratio=actionable_ratio
            )
            x_batch, s_batch = x_batch.to(device), s_batch.to(device)
            s_batch_scaled = s_batch * scale_factor

            optimizer.zero_grad()
            preds_scaled = model(x_batch)
            loss = criterion(preds_scaled, s_batch_scaled)
            loss.backward()
            optimizer.step()

        # 4. Validation Loop
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size=batch_size)
                x_val, s_val = x_val.to(device), s_val.to(device)

                # FIXED: Do not scale the validation targets
                # Unscale the predictions instead for a fair metric comparison
                preds_val_scaled = model(x_val)
                preds_val_unscaled = preds_val_scaled / scale_factor

                val_loss += criterion(preds_val_unscaled, s_val).item()

        val_loss /= val_steps

        trial.report(val_loss, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

        if val_loss < best_val_loss:
            best_val_loss = val_loss

    return best_val_loss


def generate_maps(patients, target_w=0.028):
    act_map, triv_map = [], []
    for p_idx, p in enumerate(patients):
        true_peak_indices = set(get_peak_indices_tuned(p.rewards, threshold=target_w))
        for t in range(p.T - 2):
            window_timesteps = {t, t + 1, t + 2}
            if not window_timesteps.isdisjoint(true_peak_indices):
                act_map.append((p_idx, t))
            else:
                triv_map.append((p_idx, t))
    return act_map, triv_map


def sample_independent_windows(patients, act_map, triv_map, batch_size, actionable_ratio=0.5):
    n_act = int(batch_size * actionable_ratio)
    n_triv = batch_size - n_act

    act_indices = [act_map[i] for i in np.random.choice(len(act_map), n_act)]
    triv_indices = [triv_map[i] for i in np.random.choice(len(triv_map), n_triv)]
    combined = act_indices + triv_indices
    np.random.shuffle(combined)

    contexts, targets = [], []
    for p_idx, t in combined:
        p = patients[p_idx]
        contexts.append(p.get_context(t))
        targets.append(p.get_targets(t))  # NEW: Retrieves combined array of length 4

    return torch.tensor(np.array(contexts), dtype=torch.float32), \
        torch.tensor(np.array(targets), dtype=torch.float32)


# NEW: Adjusted dimensions (input_dim and T+1 output)
class DirectRewardNet(nn.Module):
    def __init__(self, input_dim=46, T=3, hidden_dim=512, dropout_rate=0.1):
        super().__init__()
        last_dim = hidden_dim // 2
        self.trunk = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.ReLU(), nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.ReLU(), nn.Dropout(dropout_rate),
            nn.Linear(hidden_dim, last_dim), nn.LayerNorm(last_dim), nn.ReLU(),
        )
        self.target_head = nn.Linear(last_dim, T + 1)  # T + 1 output dimensions

    def forward(self, x):
        return self.target_head(self.trunk(x))


# ==========================================
# VISUALIZATION FUNCTIONS (Huber)
# ==========================================
def plot_loss_curves(train_hist, val_hist, filename="loss_curve.png", loss_name="Loss"):
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(8, 5))
    plt.plot(train_hist, label=f'Train {loss_name}', color='royalblue', linewidth=2)
    if val_hist:
        plt.plot(val_hist, label=f'Val {loss_name}', color='darkorange', linewidth=2, linestyle='--')
    plt.title(f'Training & Validation {loss_name}', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel(f'Scaled {loss_name}', fontsize=12)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()
    print(f"Saved loss curve to {filename}")


def plot_true_vs_predicted(model, patients, act_map, triv_map, filename='scatter.png', scale_factor=100.0):
    model.eval()
    all_true, all_pred = [], []
    with torch.no_grad():
        x_val, s_val = sample_independent_windows(patients, act_map, triv_map, batch_size=1000, actionable_ratio=0.5)
        s_val_scaled = s_val * scale_factor
        preds = model(x_val.to(device)).cpu().numpy()
        trues = s_val_scaled.numpy()

        all_true.extend(trues.flatten())
        all_pred.extend(preds.flatten())

    plt.figure(figsize=(8, 8))
    plt.scatter(all_true, all_pred, alpha=0.3, color='royalblue', edgecolors='none')

    max_val = max(max(all_true), max(all_pred))
    min_val = min(min(all_true), min(all_pred))
    plt.plot([min_val, max_val], [min_val, max_val], 'k--', lw=2, label='Perfect Prediction')

    plt.title('True vs Predicted Targets (Scaled)', fontsize=14, fontweight='bold')
    plt.xlabel('True Scaled Targets (Rewards + Delay)', fontsize=12)
    plt.ylabel('Predicted Scaled Targets', fontsize=12)
    plt.legend()
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()
    print(f"Saved scatter plot to {filename}")


def plot_patient_trajectories(model, patients, act_map, num_samples=4, filename='trajectories.png', scale_factor=100.0):
    model.eval()
    fig, axes = plt.subplots(num_samples, 1, figsize=(8, 3 * num_samples))
    if num_samples == 1:
        axes = [axes]

    with torch.no_grad():
        for i in range(num_samples):
            p_idx, t = random.choice(act_map)
            p = patients[p_idx]

            context = torch.tensor(p.get_context(t), dtype=torch.float32).unsqueeze(0).to(device)
            # NEW: Slicing [:3] just to plot the proxy rewards as a sequence
            true_targets = p.get_targets(t) * scale_factor
            true_rewards_scaled = true_targets[:3]

            pred_targets = model(context).squeeze(0).cpu().numpy()
            pred_rewards_scaled = pred_targets[:3]

            time_steps = np.arange(len(true_rewards_scaled))

            axes[i].plot(time_steps, true_rewards_scaled, label='True Scaled Rewards', color='green', marker='o', lw=2)
            axes[i].plot(time_steps, pred_rewards_scaled, label='Predicted Scaled Rewards', color='purple', marker='x',
                         linestyle='--', lw=2)
            axes[i].set_title(f'Patient {p.get_id()} | Start Timestep {t}', fontsize=12)
            axes[i].set_xticks(time_steps)
            axes[i].set_ylabel('Scaled Reward', fontsize=10)
            axes[i].legend()

    plt.xlabel('Lookahead Horizon (t+0, t+1, t+2)', fontsize=12)
    plt.tight_layout()
    plt.savefig(filename)
    plt.close()
    print(f"Saved trajectory plots to {filename}")


if __name__ == "__main__":
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print("Loading data for Scaled Huber...")
    dfV = pd.read_csv("HELMET_Triangular_Targets_with_V.csv")  # NEW: Updated file name
    patientArray = create_patient_objects(dfV)
    train_patients, temp_patients = train_test_split(patientArray, test_size=0.30, random_state=42)
    val_patients, test_patients = train_test_split(temp_patients, test_size=0.50, random_state=42)

    train_act, train_triv = generate_maps(train_patients)

    # ----------------------------------------
    # Run Optuna Studies (Saved to SQLite DB)
    # ----------------------------------------
    print("Starting Phase 2 Huber Optuna Study...")
    study_huber = optuna.create_study(
        direction='minimize',
        study_name='new_huber_study',
        storage='sqlite:///optuna_new_huber_study.db',
        load_if_exists=True,
        pruner=optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=5)
    )

    study_huber.optimize(lambda trial: objective_huber(trial, train_patients, val_patients, train_act, train_triv),
                       n_trials=60)

    print(f"Best Huber Params: {study_huber.best_params}")

    # ----------------------------------------
    # Train Final Model with Best Hyperparameters
    # ----------------------------------------
    best_lr = study_huber.best_params['lr']
    best_wd = study_huber.best_params['weight_decay']
    best_batch = study_huber.best_params['batch_size']
    best_scale = study_huber.best_params['scale_factor']
    best_ratio = study_huber.best_params['actionable_ratio']
    # NEW: Extract the best delta from the study
    best_delta = study_huber.best_params['delta']

    print(f"\n--- Training Final Scaled Huber Model ---")
    print(
        f"Using Best Params: LR={best_lr:.6f}, WD={best_wd:.6f}, Batch={best_batch}, "
        f"Scale={best_scale}, Ratio={best_ratio:.2f}, Delta={best_delta:.4f}")

    final_base_model = DirectRewardNet(input_dim=46, T=3).to(device)
    final_model = ScaledHuberModelWrapper(final_base_model, scale_factor=best_scale).to(device)

    optimizer = optim.AdamW(final_model.parameters(), lr=best_lr, weight_decay=best_wd)

    # NEW: Use the optimal delta for the final run
    criterion = nn.HuberLoss(delta=best_delta)

    epochs = 40
    steps_per_epoch = 100
    val_steps = 50
    train_hist, val_hist = [], []

    for epoch in range(epochs):
        final_model.train()
        train_loss = 0.0
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(
                train_patients, train_act, train_triv, batch_size=best_batch, actionable_ratio=best_ratio
            )
            x_batch, s_batch = x_batch.to(device), s_batch.to(device)
            s_batch_scaled = s_batch * best_scale

            optimizer.zero_grad()
            preds_scaled = final_model(x_batch)
            loss = criterion(preds_scaled, s_batch_scaled)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        avg_train_loss = train_loss / steps_per_epoch
        train_hist.append(avg_train_loss)

        final_model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size=best_batch)
                x_val, s_val = x_val.to(device), s_val.to(device)

                # FIXED: Unscale predictions instead of scaling targets
                preds_val_scaled = final_model(x_val)
                preds_val_unscaled = preds_val_scaled / best_scale

                v_loss = criterion(preds_val_unscaled, s_val)
                val_loss += v_loss.item()

        avg_val_loss = val_loss / val_steps
        val_hist.append(avg_val_loss)

        print(f"Epoch {epoch + 1}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    torch.save(final_model.state_dict(), 'new_rewardnet_huber_scaled_best.pth')
    print("Final model saved to new_rewardnet_huber_scaled_best.pth")

    print("\nGenerating Visualizations...")
    val_act, val_triv = generate_maps(val_patients)

    plot_loss_curves(train_hist, val_hist=val_hist, filename="new_huber_scaled_loss.png", loss_name="Huber Loss")

    plot_true_vs_predicted(final_model, val_patients, val_act, val_triv,
                           filename="new_huber_scaled_scatter.png", scale_factor=best_scale)

    plot_patient_trajectories(final_model, val_patients, val_act, num_samples=4,
                              filename="new_huber_scaled_trajectories.png", scale_factor=best_scale)
