import os
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.utils.class_weight import compute_class_weight

import torch
import torch.nn as nn
import torch.optim as optim
import optuna

import gurobipy as gp
from gurobipy import GRB
import pyepo
from pyepo.model.grb import optGrbModel

# Script generated by Google Gemini and debugged by me

# Import your network architectures and data utilities
from dataset_utils import create_patient_objects, generate_maps
from network_architectures import DirectRewardNet, ClassifierNet


# ==========================================
# 1. SETUP & SEEDS
# ==========================================
def set_seeds(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    os.environ['PYTHONHASHSEED'] = str(seed)


set_seeds(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


# ==========================================
# 2. DATA SAMPLERS & HELPERS (Shared)
# ==========================================
def get_classification_labels(s_batch, kappa=0.028):
    if not isinstance(s_batch, torch.Tensor):
        s_batch = torch.tensor(s_batch, dtype=torch.float32)
    objective_values = s_batch.clone()
    objective_values[:, :3] = objective_values[:, :3] - kappa
    return torch.argmax(objective_values, dim=1)


def calculate_class_weights(patients, kappa=0.028):
    all_labels = []
    for p in patients:
        for t in range(p.T - 2):
            targets = p.get_targets(t)
            obj_vals = np.copy(targets)
            obj_vals[:3] -= kappa
            all_labels.append(np.argmax(obj_vals))
    classes = np.array([0, 1, 2, 3])
    weights = compute_class_weight(class_weight='balanced', classes=classes, y=all_labels)
    return torch.tensor(weights, dtype=torch.float32)


def sample_independent_windows(patients, act_map, triv_map, batch_size, actionable_ratio=0.5):
    n_act = int(batch_size * actionable_ratio)
    n_triv = batch_size - n_act
    act_indices = [act_map[i] for i in np.random.choice(len(act_map), n_act)]
    triv_indices = [triv_map[i] for i in np.random.choice(len(triv_map), n_triv)]
    combined = act_indices + triv_indices
    np.random.shuffle(combined)
    contexts, targets = [], []
    for p_idx, t in combined:
        p = patients[p_idx]
        contexts.append(p.get_context(t))
        targets.append(p.get_targets(t))
    return torch.tensor(np.array(contexts), dtype=torch.float32), torch.tensor(np.array(targets), dtype=torch.float32)


def sample_natural_independent_windows(patients, batch_size):
    all_x, all_s = [], []
    patient_indices = np.random.choice(len(patients), batch_size, replace=True)
    for p_idx in patient_indices:
        p = patients[p_idx]
        t = np.random.randint(0, p.T - 2)
        all_x.append(p.get_context(t))
        all_s.append(p.get_targets(t))
    return torch.tensor(np.array(all_x), dtype=torch.float32), torch.tensor(np.array(all_s), dtype=torch.float32)


# SPO+ Specific Helpers
def sample_hospital_shifts_pyepo(patients, act_map, triv_map, batch_size, n_patients, actionable_ratio=0.5):
    all_x, all_s = [], []
    for _ in range(batch_size):
        n_act = int(n_patients * actionable_ratio)
        n_triv = n_patients - n_act
        act_idx = [act_map[i] for i in np.random.choice(len(act_map), n_act, replace=True)]
        triv_idx = [triv_map[i] for i in np.random.choice(len(triv_map), n_triv, replace=True)]
        shift_participants = act_idx + triv_idx
        np.random.shuffle(shift_participants)
        inst_x, inst_s = [], []
        for p_idx, t in shift_participants:
            p = patients[p_idx]
            inst_x.append(p.get_context(t))
            inst_s.extend(p.get_targets(t))
        all_x.extend(inst_x)
        all_s.append(inst_s)
    return torch.tensor(np.array(all_x), dtype=torch.float32), torch.tensor(np.array(all_s), dtype=torch.float32)


def sample_natural_hospital_shifts_pyepo(patients, batch_size, n_patients):
    all_x, all_s = [], []
    for _ in range(batch_size):
        shift_participants = np.random.choice(len(patients), n_patients, replace=True)
        inst_x, inst_s = [], []
        for p_idx in shift_participants:
            p = patients[p_idx]
            t = np.random.randint(0, p.T - 2)
            inst_x.append(p.get_context(t))
            inst_s.extend(p.get_targets(t))
        all_x.extend(inst_x)
        all_s.append(inst_s)
    return torch.tensor(np.array(all_x), dtype=torch.float32), torch.tensor(np.array(all_s), dtype=torch.float32)


class NeuroICUSchedulingModel(optGrbModel):
    def __init__(self, N, T, R):
        self.N, self.T, self.R = N, T, R
        super().__init__()

    def _getModel(self):
        env = gp.Env(empty=True)
        env.setParam("OutputFlag", 0)
        env.start()
        m = gp.Model("NeuroICUScheduling_Rolling", env=env)
        x = m.addVars(self.N * (self.T + 1), vtype=GRB.BINARY, name="x")

        def get_x(i, t):
            return x[i * (self.T + 1) + t]

        def get_x_later(i):
            return x[i * (self.T + 1) + self.T]

        for t in range(self.T):
            m.addConstr(gp.quicksum(get_x(i, t) for i in range(self.N)) <= self.R)
        for i in range(self.N):
            m.addConstr(gp.quicksum(get_x(i, t) for t in range(self.T)) + get_x_later(i) == 1)
        return m, x


# ==========================================
# 3. TRAINING LOOPS WITH EARLY STOPPING
# ==========================================
def train_standard_regression(model, optimizer, criterion, train_patients, val_patients, train_act, train_triv,
                              batch_size, actionable_ratio, scale_factor, epochs, save_path, patience=20):
    best_val_loss = float('inf')
    epochs_no_improve = 0
    steps_per_epoch = 100
    val_steps = 50

    for epoch in range(epochs):
        model.train()
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(train_patients, train_act, train_triv, batch_size,
                                                          actionable_ratio)

            optimizer.zero_grad()
            # Scale both the predictions and the targets to compute loss
            preds_scaled = model(x_batch.to(device)) * scale_factor
            s_batch_scaled = s_batch.to(device) * scale_factor

            loss = criterion(preds_scaled, s_batch_scaled)
            loss.backward()
            optimizer.step()

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size)
                # Unscaled evaluation for a fair comparison against targets
                preds_unscaled = model(x_val.to(device))
                val_loss += criterion(preds_unscaled, s_val.to(device)).item()

        val_loss /= val_steps

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), save_path)
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1}. Best Val Loss: {best_val_loss:.4f}")
                break
    print(f"Saved best regression model to {save_path}")


def train_classifier(model, optimizer, criterion, train_patients, val_patients, train_act, train_triv, batch_size,
                     actionable_ratio, epochs, save_path, patience=20):
    best_macro_f1 = 0.0
    epochs_no_improve = 0
    steps_per_epoch = 100
    val_steps = 50

    for epoch in range(epochs):
        model.train()
        for _ in range(steps_per_epoch):
            x_batch, s_batch = sample_independent_windows(train_patients, train_act, train_triv, batch_size,
                                                          actionable_ratio)
            labels = get_classification_labels(s_batch).to(device)
            optimizer.zero_grad()
            loss = criterion(model(x_batch.to(device)), labels)
            loss.backward()
            optimizer.step()

        model.eval()
        all_val_preds, all_val_labels = [], []
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val = sample_natural_independent_windows(val_patients, batch_size)
                all_val_labels.extend(get_classification_labels(s_val).numpy())
                all_val_preds.extend(torch.argmax(model(x_val.to(device)), dim=1).cpu().numpy())

        macro_f1 = f1_score(all_val_labels, all_val_preds, average='macro', zero_division=0)

        if macro_f1 > best_macro_f1:
            best_macro_f1 = macro_f1
            torch.save(model.state_dict(), save_path)
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1}. Best Macro F1: {best_macro_f1:.4f}")
                break
    print(f"Saved best classifier to {save_path}")


def train_spo_plus(model, optimizer, train_patients, val_patients, train_act, train_triv, batch_size, actionable_ratio,
                   scale_factor, epochs, save_path, patience=35):
    N, T, R = 30, 3, 3
    opt_model = NeuroICUSchedulingModel(N=N, T=T, R=R)
    spo_loss_fn = pyepo.func.SPOPlus(opt_model, processes=1)

    kappa_mask_unscaled = torch.ones(N * (T + 1)).to(device)
    for i in range(N): kappa_mask_unscaled[i * (T + 1) + T] = 0.0
    kappa_mask_unscaled *= 0.028
    kappa_mask_base = kappa_mask_unscaled * scale_factor

    best_val_loss = float('inf')
    epochs_no_improve = 0
    steps_per_epoch, val_steps = 100, 50

    for epoch in range(epochs):
        model.train()
        for _ in range(steps_per_epoch):
            x_batch, s_batch_flat = sample_hospital_shifts_pyepo(train_patients, train_act, train_triv, batch_size, N,
                                                                 actionable_ratio)
            s_preds_flat_scaled = model(x_batch.to(device)).view(batch_size, N * (T + 1))

            c_preds = kappa_mask_base.expand(batch_size, -1) - s_preds_flat_scaled
            c_true = kappa_mask_base.expand(batch_size, -1) - (s_batch_flat.to(device) * scale_factor)

            w_batch, z_batch = [], []
            for i in range(batch_size):
                opt_model.setObj(c_true[i].detach().cpu().numpy())
                sol, obj = opt_model.solve()
                w_batch.append(sol);
                z_batch.append([obj])

            loss = spo_loss_fn(c_preds, c_true, torch.tensor(np.array(w_batch), dtype=torch.float32).to(device),
                               torch.tensor(np.array(z_batch), dtype=torch.float32).to(device))
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for _ in range(val_steps):
                x_val, s_val_flat = sample_natural_hospital_shifts_pyepo(val_patients, batch_size, N)
                s_preds_flat_unscaled = model(x_val.to(device)).view(batch_size, N * (T + 1)) / scale_factor
                c_preds_val = kappa_mask_unscaled.expand(batch_size, -1) - s_preds_flat_unscaled
                c_true_val = kappa_mask_unscaled.expand(batch_size, -1) - s_val_flat.to(device)

                w_batch, z_batch = [], []
                for i in range(batch_size):
                    opt_model.setObj(c_true_val[i].detach().cpu().numpy())
                    sol, obj = opt_model.solve()
                    w_batch.append(sol)
                    z_batch.append([obj])

                val_loss += spo_loss_fn(c_preds_val, c_true_val,
                                        torch.tensor(np.array(w_batch), dtype=torch.float32).to(device),
                                        torch.tensor(np.array(z_batch), dtype=torch.float32).to(device)).item()

        avg_val_loss = val_loss / val_steps
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            torch.save(model.state_dict(), save_path)
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= patience:
                print(f"Early stopping at epoch {epoch + 1}. Best Val SPO+ Loss: {best_val_loss:.4f}")
                break
    print(f"Saved best SPO+ model to {save_path}")


# ==========================================
# 4. EXECUTION
# ==========================================
if __name__ == "__main__":
    MAX_EPOCHS = 150

    print("Loading Data & Creating Splits...")
    dfV = pd.read_csv("HELMET_Triangular_Targets_with_V.csv")
    patientArray = create_patient_objects(dfV)
    train_patients, temp_patients = train_test_split(patientArray, test_size=0.30, random_state=42)
    val_patients, test_patients = train_test_split(temp_patients, test_size=0.50, random_state=42)
    train_act, train_triv = generate_maps(train_patients)

    print("\n--- 1. Training MSE Model ---")
    p_mse = optuna.load_study(study_name='new_mse_study', storage='sqlite:///optuna_new_mse_study.db').best_params
    m_mse = DirectRewardNet(input_dim=46, T=3, hidden_dim=p_mse['hidden_dim']).to(device)
    train_standard_regression(m_mse, optim.AdamW(m_mse.parameters(), lr=p_mse['lr'],
                                                 weight_decay=p_mse.get('weight_decay', 1e-4)), nn.MSELoss(),
                              train_patients, val_patients, train_act, train_triv, p_mse['batch_size'],
                              p_mse['actionable_ratio'], p_mse['scale_factor'], MAX_EPOCHS, 'final_mse.pth')

    print("\n--- 2. Training Huber Model ---")
    p_hub = optuna.load_study(study_name='new_huber_study', storage='sqlite:///optuna_new_huber_study.db').best_params
    m_hub = DirectRewardNet(input_dim=46, T=3, hidden_dim=p_hub['hidden_dim']).to(device)
    train_standard_regression(m_hub, optim.AdamW(m_hub.parameters(), lr=p_hub['lr'],
                                                 weight_decay=p_hub.get('weight_decay', 1e-4)),
                              nn.HuberLoss(delta=p_hub.get('delta', 1.0)), train_patients, val_patients, train_act,
                              train_triv, p_hub['batch_size'], p_hub['actionable_ratio'], p_hub['scale_factor'],
                              MAX_EPOCHS, 'final_huber.pth')

    print("\n--- 3. Training Classifier Model ---")
    p_cls = optuna.load_study(study_name='new_classifier_study',
                              storage='sqlite:///optuna_new_classifier_study.db').best_params
    m_cls = ClassifierNet(input_dim=46, hidden_dim=p_cls['hidden_dim']).to(device)
    c_weights = calculate_class_weights(train_patients)
    train_classifier(m_cls, optim.AdamW(m_cls.parameters(), lr=p_cls['lr'], weight_decay=p_cls['weight_decay']),
                     nn.CrossEntropyLoss(weight=c_weights.to(device)), train_patients, val_patients, train_act,
                     train_triv, p_cls['batch_size'], p_cls['actionable_ratio'], MAX_EPOCHS, 'final_classifier.pth')

    print("\n--- 4. Training SPO+ Model ---")
    p_spo = optuna.load_study(study_name='new_spo_dfl_study', storage='sqlite:///optuna_new_spo_dfl.db').best_params
    m_spo = DirectRewardNet(input_dim=46, T=3, hidden_dim=p_spo['hidden_dim']).to(device)
    train_spo_plus(m_spo, optim.AdamW(m_spo.parameters(), lr=p_spo['lr'], weight_decay=p_spo.get('weight_decay', 1e-4)),
                   train_patients, val_patients, train_act, train_triv, p_spo['batch_size'],
                   p_spo['train_actionable_ratio'], p_spo['scale_factor'], MAX_EPOCHS, 'final_spo.pth')

    print("\nAll final models trained! Proceed to new_evaluate_test_set.py")
